# Generated by Django 6.0.6 on 2026-07-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('flag_code', models.CharField(blank=True, help_text='ISO Country Code (e.g. AE, SA, RO) or CSS flag class', max_length=10, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('description', models.TextField(help_text='Detailed recruitment info for this destination')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.destination'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
