# Generated by Django 6.0.6 on 2026-07-05 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes regarding resolution', null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Defines display ordering sequences')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('recruitment', 'Recruitment Drive'), ('placed_candidates', 'Placed Candidates'), ('office', 'Office & Staff'), ('events', 'Corporate Events')], default='recruitment', max_length=50)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Elevate Workforce', max_length=100)),
                ('default_meta_title', models.CharField(default='Elevate Workforce | Premier Overseas Recruitment', max_length=150)),
                ('default_meta_description', models.TextField(default='Elevate Workforce is a leading international recruitment agency bridging skilled candidates with global industry opportunities.')),
                ('google_analytics_id', models.CharField(blank=True, help_text='UA-XXXXXX-X or G-XXXXXXXXXX', max_length=50, null=True)),
                ('robots_txt', models.TextField(default='User-agent: *\nDisallow: /admin/\nDisallow: /users/dashboard/')),
                ('schema_markup', models.TextField(blank=True, help_text='JSON-LD Schema Markup to inject globally', null=True)),
                ('sitemap_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO & System Settings',
                'verbose_name_plural': 'SEO & System Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('candidate', 'Placed Candidate'), ('employer', 'Corporate Partner / Client')], default='candidate', max_length=20)),
                ('designation', models.CharField(help_text='E.g., Piping Supervisor at Saudi Aramco, or Senior HR Director', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating on scale of 1-5')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('thumbnail', models.ImageField(upload_to='blogs/%Y/%m/')),
                ('content', models.TextField(help_text='Detailed HTML or Markdown content')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
